import { Image } from "expo-image";
import { memo } from "react";
import { useWindowDimensions } from "react-native";
import { useAppearancePreferences } from "../settings/appearance/AppearancePreferencesProvider";

/**
 * Backdrop artwork for the thread canvas, currently only Cyberpunk's neon
 * splatter. The same four SVGs the web app uses, generated by
 * scripts/generate-cyberpunk-splatter.ts.
 *
 * Rendered through expo-image rather than react-native-svg: each cluster is
 * around 600 vector nodes, and react-native-svg would turn every one of them
 * into a native shape it re-walks on layout. expo-image hands the file to the
 * platform SVG decoder, which rasterizes once and caches the bitmap, so the
 * backdrop costs two static image layers no matter how detailed the art gets.
 *
 * Geometry mirrors the phone branch of the web rule in apps/web/src/index.css:
 * two corner clusters, the lower one lifted clear of the composer. Keep the
 * two in step when either moves.
 */
const CLUSTERS = {
  dark: {
    a: require("../../../assets/themes/cyberpunk-splatter-dark-a.svg"),
    b: require("../../../assets/themes/cyberpunk-splatter-dark-b.svg"),
  },
  light: {
    a: require("../../../assets/themes/cyberpunk-splatter-light-a.svg"),
    b: require("../../../assets/themes/cyberpunk-splatter-light-b.svg"),
  },
} as const;

/** Cluster width as a multiple of screen width; the art is square. */
const LEAD_SCALE = 1.25;
const TRAILING_SCALE = 1.3;
/** Keeps the trailing cluster's largest splat out from under the composer. */
const TRAILING_BOTTOM_FRACTION = 0.12;
const TRAILING_LEFT_FRACTION = -0.18;

export const ThreadCanvasBackdrop = memo(function ThreadCanvasBackdrop() {
  const { themeId, themeAppearance } = useAppearancePreferences();
  const { width, height } = useWindowDimensions();

  if (themeId !== "cyberpunk") return null;

  const cluster = CLUSTERS[themeAppearance === "dark" ? "dark" : "light"];
  const lead = width * LEAD_SCALE;
  const trailing = width * TRAILING_SCALE;

  return (
    <>
      <Image
        source={cluster.a}
        style={{ position: "absolute", top: 0, right: 0, width: lead, height: lead }}
        contentFit="contain"
        // The art never changes once a theme is picked, so decoding it again on
        // every thread switch would be pure waste.
        cachePolicy="memory-disk"
      />
      <Image
        source={cluster.b}
        style={{
          position: "absolute",
          left: width * TRAILING_LEFT_FRACTION,
          bottom: height * TRAILING_BOTTOM_FRACTION,
          width: trailing,
          height: trailing,
        }}
        contentFit="contain"
        cachePolicy="memory-disk"
      />
    </>
  );
});
